### ISSUE TITLE
Fails to save JSON for channel name with spaces

### ISSUE THREAD

**Issue by DnanaDev** [Xosrov/YouTube-Indexer#1]
Thanks for the great little tool. 
The script fails if you try to index a channel which has a space in the name even when using the non-spaced YouTube identifier. I have worked around the issue but it might be useful to fix.

Ex, collector.py -c  LateLateShowwCraigFergusonArchive

Traceback (most recent call last):
  File "youtube_collector.py", line 235, in <module>
    sample.getAndSaveVideos(creator)
  File "youtube_collector.py", line 151, in getAndSaveVideos
    self.saveToFile(channelName, data)
  File "youtube_collector.py", line 97, in saveToFile
    with open(path.join(_filePath, f"{_FileNamePrefix + channelName}.json"), 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/apple/Desktop/Other_Programming/VE_Late Late Show w/ Craig Ferguson Archive.json'

Edit: Thanks for correcting the issue. It was indeed a sanitisation issue due to the name of the channel containing '/'. Ignore the title of the issue.

**Comment by Xosrov** [comment]
Try escaping the spaces or using quotation marks in the new update:
collector.py -c "Late Late Showw Craig Ferguson Archive"
or 
collector.py -c Late\ Late\ Showw\ Craig\ Ferguson\ Archive

The problem was trying to save the file as the channel name, i had to sanitize the channel name first to make sure it was a file and not a directory. I decided to use a python package instead to account for any possible future problems as well. 
Thanks for reporting this
